### PR TITLE
all login pages

### PR DESCRIPTION
**Pull request by mati-1**
[PM-977](https://playmakerpro.atlassian.net/browse/PM-977)
[PM-975](https://playmakerpro.atlassian.net/browse/PM-975)
[PM-976](https://playmakerpro.atlassian.net/browse/PM-976)

- added simple differentiation between emails for change routing (login or register)
- added form validation
- added loading state and icon for button
- added page for login with code
- added login context
- added working code input component
- added reset password page
- added temporary loading states etc. for imiting sending api requests

### CODE REVIEW

**Review by dejwi — CHANGES_REQUESTED** [review]
Nice💯

Can you somehow implement ability to paste code? I'm sure most people will just copy the code from email and try to paste it

**Comment by mati-1** [comment]
> Nice💯
> 
> Can you somehow implement ability to paste code? I'm sure most people will just copy the code from email and try to paste it
true, i ll change it

**Comment by mati-1** [comment]
> Nice💯
> 
> Can you somehow implement ability to paste code? I'm sure most people will just copy the code from email and try to paste it

true, i ll change it

**Review by dejwi — APPROVED** [review]
excellent🎉

**Pull request merged**
